FROM balenalib/%%BALENA_MACHINE_NAME%%-node:6-run

WORKDIR /usr/src/app

RUN install_packages curl

COPY package*.json ./
RUN npm install --production

COPY . ./

HEALTHCHECK --start-period=5s --timeout=30s --interval=5s --retries=1 \
    CMD curl --silent --fail localhost:8080/status

CMD ["node", "app.js"]
