FROM resin/%%RESIN_MACHINE_NAME%%-alpine-node:9-slim

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --production

COPY . ./

HEALTHCHECK --start-period=10s --timeout=30s --interval=5s --retries=1 \
            CMD curl --silent --fail localhost/status

CMD ["node", "app.js"]
